### ISSUE TITLE
Buttons using jQuery in href don't work in Firefox

### ISSUE THREAD

**Issue by filip1** [webvariants/policat#11] opened 2018-12-18 14:44 UTC
Several backend buttons (such as "Edit target list" and some "Cancel" buttons) use jQuery inside the `javascript:` href attribute – for example, on the target configuration page of an action – https://www.policat.org/action/target/592

```html
<a id="edit-btn" class="btn" href="javascript:$('#edit').show();$('#edit-btn').addClass('hide'); ">Edit target-list</a>
```

In Firefox, these buttons don't work. Instead, when clicking such a button, the whole page is replaced with a blank page showing "[object Object]" – the [return value of the jQuery code](https://stackoverflow.com/questions/18703133/using-jquery-inside-of-an-href-tag).

As a quick fix for it to work in Firefox, the whole JS code in the href attribute could be wrapped in an anonymous function like this:

```javascript
(function(){$('#edit').show();$('#edit-btn').addClass('hide');})();
```

**Comment by mcnilz** [comment] 2018-12-19 13:35
I could not reproduce it in my Firefox but I committed a fix in the [develop](https://github.com/webvariants/policat/commits/develop) branch. Do you have an instance where you can test it? https://github.com/webvariants/policat/commit/084dde12692612fb426d91481c4b9d633b403034

**Comment by filip1** [comment] 2018-12-19 15:02
Unfortunately I don't have an instance for testing, and I don't think I'm proficient enough to set one up without spending days trying.

When I change the href attribute like in 084dde12692612fb426d91481c4b9d633b403034 client-side through the browser dev tools, that does fix the issue.

If it helps, I tested policat.org in Firefox 60.4.0esr (the latest version on the ESR channel) on Windows, all add-ons disabled.

**Comment by mcnilz** [comment] 2018-12-19 15:05
ok I will deploy on policat.org tomorrow.

**Comment by mcnilz** [comment] 2018-12-20 07:54
just deployed on policat.org.

**Closed** 2018-12-20 14:51 UTC
